.Dd June 06, 2026
.Os Linux
.Dt MPNEXT 1 LOCAL
.Sh NAME
.Nm mpnext
.Nd jump to next song in mploop music player
.Sh SYNOPSIS
.Nm mpnext
.Op Ar count
.Sh DESCRIPTION
.Nm mpnext
is a tool to jump to next song in the
.Xr mploop 1
music player.
.Sh OPTIONS
.Bl -tag -width "count"
.It count
The number of songs to jump forward, default 1
.Sh "EXIT STATUS"
.Nm mpnext
exits with zero exit status for success. If there's an error such as
invoking
.Nm mpnext
with unsupported command-line arguments, it returns with a nonzero
exit status.
.Sh ENVIRONMENT
.Nm mpnext
uses the following environment variables:
.Pp
.Bl -column HOME -compact
.It Ev HOME Ta the home directory of the user
.El
.Sh "SEE ALSO"
.Xr mploop 1
.Sh HISTORY
.Xr mploop 1
was created in September to November 2023. It has been maintained since.
.Sh DISTRIBUTION
.Xr mploop 1
is available at https://github.com/jmtilli/mploop
.Sh BUGS
No bugs known in
.Nm mpnext .
.Sh AUTHOR
Juha-Matti Tilli (juha-matti.tilli@iki.fi)
.Sh COPYRIGHT
Copyright \(co 2023-4,2026 Juha-Matti Tilli
.Pp
Licensed under the MIT license.
