.Dd June 06, 2026
.Os Linux
.Dt MPREWIND 1 LOCAL
.Sh NAME
.Nm mprewind
.Nd rewind the current song in the mploop player
.Sh SYNOPSIS
.Nm mprewind
.Sh DESCRIPTION
.Nm mprewind
is a tool to rewind the current song in the
.Xr mploop 1
music player.
.Sh "EXIT STATUS"
.Nm mprewind
exits with zero exit status for success. If there's an error such as
invoking
.Nm mprewind
with unsupported command-line arguments, it returns with a nonzero
exit status.
.Sh ENVIRONMENT
.Nm mprewind
uses the following environment variables:
.Pp
.Bl -column HOME -compact
.It Ev HOME Ta the home directory of the user
.El
.Sh "SEE ALSO"
.Xr mploop 1
.Sh HISTORY
.Xr mploop 1
was created in September to November 2023. It has been maintained since.
.Sh DISTRIBUTION
.Xr mploop 1
is available at https://github.com/jmtilli/mploop
.Sh BUGS
If the song is longer than 5 hours,
.Nm mprewind
does not seek to its beginning but rather seeks back 5 hours.
.Sh AUTHOR
Juha-Matti Tilli (juha-matti.tilli@iki.fi)
.Sh COPYRIGHT
Copyright \(co 2023-4,2026 Juha-Matti Tilli
.Pp
Licensed under the MIT license.
